### ISSUE TITLE
Events are no longer posting to site

### ISSUE THREAD

**Issue by eebbesen** [OpenTwinCities/opentwincities.github.com#61]
The sites below used to get Meetup events posted to them automatically, but the 09/12/19 Ukraine event is the last one to have posted. Figure out why this stopped working and see if we can get it working again.

* https://www.opentwincities.org/events/
* https://www.opentwincities.org/posts/
* https://www.opentwincities.org

**Comment by benjifs** [comment]
The [opentwincities-bot](https://github.com/OpenTwinCities/site_bot) that was automatically pushing those changes is no longer working. Meetup deprecated API keys on August 15th, 2019 and to get access to v3 of the API, you need to have a Meetup Pro subscription to generate the proper token. 

You can find more info below:
https://help.meetup.com/hc/en-us/articles/360028901812-Using-Meetup-s-API

Another option would be instead use the [RSS feed](https://www.meetup.com/OpenTwinCities/events/rss) as that does not require an API key

**Comment by eebbesen** [comment]
Workaround:
1. Run site_bot manually
1. Rename files to match old standard
1. Change `title` to remove duplicate date
1. Change `event_date` -- remove `'`s to prevent format errors on build

**Comment by eebbesen** [comment]
This looks to be working now
